### ISSUE TITLE
Luakit fails to start since last update

### ISSUE THREAD

**Issue by zoqaeski** [mason-larobina/luakit#200]
Since the last update of my system earlier tonight, luakit fails to start. It appears to hang on loading the rc.lua file, and [for some users dmesg reports a segfault](https://bbs.archlinux.org/viewtopic.php?pid=1262912#p1262912).

Apparently this is caused by a bug in webkitgtk, or nvidia drivers (I have an AMD card! with Catalyst o_O), and might be upstream, but every other webkitgtk brower I’ve tried doesn’t seem to have an issue. I’ve tried upgrading and downgrading webkitgtk, but that hasn’t solved anything.

**Comment by mason-larobina** [comment]
By all accounts this was fixed upstream and the hard coding of an arch isn't really a fix. Please re-open if this is still a problem.
