### ISSUE TITLE
How to "disable/ hide" Command / input line from bottom of luakit?

### ISSUE THREAD

**Issue by Freisturz** [mason-larobina/luakit#290]
Hello,

I'm making my raspberry as A Info screen with luakit, but only issue now is that command / input field is showing up down there with websites address 
I'd like to get rid of it 
![vistainfo](https://cloud.githubusercontent.com/assets/14557673/9991588/df87ac4a-6073-11e5-82bc-42b6dc73c910.PNG)
any suggestion ?

**Comment by o-jasper** [comment]
Comment out the `w.layout:pack(...)` statements in `config/window.lua` file, for the status elements and input bar.

Trying it, seems like it goes into insert mode appropriately, and you cannot type in commands for lack of widget to type it in. Nevertheless, keep in mind that modes still exist.

**Comment by Freisturz** [comment]
Thanks for the help I were then looking at right place but didint know which lines effects to it
Trying it tomorrow when at office again.

**Comment by Freisturz** [comment]
Hey,

Didin't work as I planned. So is there any other way to delete that black field from bottom.
Tried to uncomment # or put false to those and seems that the whole browser disappears from startup

**Comment by rozcietrzewiacz** [comment]
@Freisturz: I just tested and it worked. Maybe you had a typo in your edit? Here'show it should look like:

- near line 100 of `~/.local/share/luakit/window.lua`:

```lua
     -- Pack status bar elements
     local s = w.sbar
     s.layout:pack(l.ebox)
     s.layout:pack(s.sep, { expand = true, fill = true })
     s.layout:pack(r.ebox)
     s.ebox.child = s.layout
 --    w.layout:pack(s.ebox)
```

- ... and near line 110 in the same file:

```lua
     -- Pack input bar
     local i = w.ibar
     i.layout:pack(i.prompt)
     i.layout:pack(i.input, { expand = true, fill = true })
     i.ebox.child = i.layout
 --    w.layout:pack(i.ebox)
```

**Comment by Freisturz** [comment]
Thanks that worked flawlessly, well made a typo on that nad that messed whole thing up. Thanks!
