### ISSUE TITLE
help page is gone (and history)

### ISSUE THREAD

**Issue by dahn-d** [mason-larobina/luakit#292]
i pressed D and after restart help page has gone (why?)
currently when i type `:help` only blank page appears with *Luakit Help* underlined header
and history is disfunctional. `:history` is always empty
i need them back :)
im new to luakit
also i did a few changes in my configs but `luakit -k` says that config is ok

**Comment by dahn-d** [comment]
omg i did something and everything is back
really weird...
i did an error in globals.lua, restarted, problem appeared, corrected the error, restarted, problem still here, did another typo in code, couldnt start ofc, corected, restarted, problem disappeared. lol.
all these time i was changing only `domain_props` structure or whatever it called in lua, and errors was coz of incorrect syntax like trying to wrap fields in quotes

anyway, sorry for creating issue

**Comment by o-jasper** [comment]
No prob, can't doubt whether to submit a issue forever. Just try fix it yourself a bit,(also look at any error output) and try make sure the issue doesnt already exists. At least that's how i see it.
